### ISSUE TITLE
Redis plugin performance

### ISSUE THREAD

**Issue by jkimalane** [syslog-ng/syslog-ng#2959] opened 2019-10-04 10:12 UTC
what is the estimate EPS for redis destination plugin? I have been testing the redis plugin and currently facing performance issues. Version 3.23.1 behaves bit oddly when a log statement has multiple destinations: one file and one redis
```
log {
    source(s_remote);
    destination(d_3tier_without_host_in_file_name);
    destination(d_3tier_redis_stream_stdmsg);
    flags(flow-control, final);
};
```

when redis is enabled EPS drops multiple times. Should I enable disk based buffering so that large memory buffer is allocated for keeping up with the EPS flow?

**Comment by alltilla** [comment] 2019-10-04 10:34
Hi,
Could you send your `redis` destination config block?
Thanks!

**Comment by jkimalane** [comment] 2019-10-04 10:51
Here it is
`destination d_3tier_redis_stream_stdmsg {
    redis(
        host("172.1.1.1")
        port(7379)
        command(
            "XADD",
            "stream.${X_TOKEN_REALM}.${X_TOKEN_APP}.${X_TOKEN_LOG}",
            "MAXLEN", "~", "9000", "*",
            "date", "${R_ISODATE}",
            "host", "${HOST}",
            "header", "${MSGHDR}"
            "message", "${MSG}"
        )
        log-fifo-size(500000)
        persist-name("d_3tier_redis_stream_stdmsg")
  );
};`

**Comment by jkimalane** [comment] 2019-10-07 13:56
As far I know and according to the documentation, syslog-ng implementation of the redis client does not support pipelining. This could be one possible solution to increase EPS performance.

**Comment by szemere** [comment] 2019-10-07 14:05
Hello @jkimalane ,
 I am putting together a Redis environment to test out some use-cases with your config. (Thank you for sending it for us!)

 I will write you back with my findings.

Br,
Laci

**Comment by szemere** [comment] 2019-10-16 06:40
Hello @jkimalane ,
 Implementing pipelining was a good idea! I also managed to improve the redis destination drivers performance without pipelining. But batch-lines was the deal breaker.
 Can you compile and test syslog-ng from source code in your environment?

Br,
Laci

**Comment by jkimalane** [comment] 2019-10-17 10:45
I'm wondering, how exactly did you test the performance impact of your changes? Could you please share so I could try to replicate it in my test environment.

**Comment by szemere** [comment] 2019-10-17 11:04
Hello,
 I used [mmwatch](https://github.com/cloudflare/cloudflare-blog/tree/master/2017-06-29-ssdp) to monitor the stats of syslog-ng, and examined the "written" counter:

`mmwatch "/install/sbin/syslog-ng-ctl stats"`

**Comment by jkimalane** [comment] 2019-10-17 11:21
And the syslog-ng config you use is similar to the snipes I posted here at the beginning of this thread? If so then that's strange as I can't get past 1K EPS.

**Comment by szemere** [comment] 2019-10-17 11:45
Yes. Exactly identical. Can you measure your network latency between the Syslog-ng instance and the Redis server? Prior to one command, there must be multiple message exchange between them, and network latency will sum up. My test envrionment:
```
50 packets transmitted, 50 received, 0% packet loss, time 49072ms
rtt min/avg/max/mdev = 1.711/3.805/6.383/1.046 ms
```
Also: Do you know the load on your Redis server? Mine was pretty low, since it was only a test machine. (As a good start, maybe you can test your config with a temporary instance on localhost.)

One last thought: During my valgrind measurements I found that syslog-ng spend significant amount of time with the template parsing. In my case `stream.${X_TOKEN_REALM}.${X_TOKEN_APP}.${X_TOKEN_LOG}` those variables were left empty. I assume they are declared earlier in your config.
Maybe you can measure your performance with a minimal command, so we can identify the bottleneck in your system.

Br,
Laci

**Comment by jkimalane** [comment] 2019-10-17 12:39
Indeed, match function with semi-complex regex is used for populating those X_  macros.

```filter f_3tier_common {
    match('^(prod|test|wss)\.([^\.]{1,})\.([\.\-\w]{1,})', value("X_TAG"), flags(store-matches));
};```

I change redis destination so that in case redis plugin can't handle the incoming flow of messages, memory and disk buffers are used for mitigation as otherwise the primary file log destination will radically slow down as well.

```destination d_3tier_redis_stream_stdmsg {
    redis(
        host("172.1.1.1")
        port(7379)
        command(
            "XADD",
            "stream.${X_TOKEN_REALM}.${X_TOKEN_APP}.${X_TOKEN_LOG}",
            "MAXLEN", "~", "9000", "*",
            "date", "${R_ISODATE}",
            "host", "${HOST}",
            "header", "${MSGHDR}"
            "message", "${MSG}"
        )
        batch_lines(5)
        disk-buffer(
            mem-buf-length(419430400)
            disk-buf-size(209715200)
            reliable(no)
            dir("/data/cache")
        )
        log-fifo-size(500000)
        persist-name("d_3tier_redis_stream_stdmsg")
  );
};```

**Comment by szemere** [comment] 2019-10-18 08:21
Hello @jkimalane ,
 I am trying to reproduce the mentioned slowness, but I have no luck yet. Could you please test my other ideas?
 - Examine network latency
 - Simpler commands for a short testing period (less macro to evaluate)
 - Temporary Redis server at localhost

If you can create a temporary new setup, may I suggest using `loggen` as a source on your logpath? It gives a much smother message flow for testing purposes. My command was:

`loggen -T -S -s 250 -r 50000 127.0.0.1 8001`

Using a simple network source in my minimalist config:

```
source s_net1 {
    tcp(
        port(8001)
    );
};
```

Best regards,
Laci

**Comment by jkimalane** [comment] 2019-10-25 13:16
Thank's for those debugging hints. Next week I'll dig more deeply into this issue. BTW, any chance that anytime soon your changes can be merged into main-line branch?

**Comment by szemere** [comment] 2019-10-28 13:50
Hello @jkimalane,
 I removed the WIP flag from the PR. Currently I am waiting for performance feedbacks and review comments*. If everything goes well, it can be included in the next release.

\* You can also be a reviewer! If you have any concern about the code, please feel free to send your comments. Maybe you can not approve the pull request, but sooner you point out my programming errors, the sooner I can correct them.

Br,
Laci

**Comment by jkimalane** [comment] 2019-11-01 12:26
Hi @szemere ,
with tweaking, more like removing all the complexity I have in my syslog-ng configuration, I was finally able to replicate the performance you showed right after implementing pipelining. But behind those number are few gotchas. One of those is the message size. You used 256 bytes, I tried 4K and 8K sizes. With 4K, the throughput was 40K EPS and with 8K it was 20K, probably these numbers are fine at least there is some sort of size/EPS correlation.  I used legacy BSD syslog protocol,  IETF RFC5424 throughput is bit higher, messages size 4K reached 49K EPS.
I suspect that the reason why I saw slow EPS throughput is related to the way we are planning to use redis plugin. Steady EPS throughput can be achieved with "static" redis stream key, but when dynamic key is used ie. key is derived from the PRGNAME message field, then EPS throughput drops drastically. I still have to do few additional tests to verify this.

**Comment by szemere** [comment] 2019-11-04 08:39
Hi @jkimalane,
 thank you for the feedback.
 
 My first idea: If the range of your PRGNAMES are limited, or only few of them gives the bulk amount of messages (80/20 rule), you can create a dedicated destinations for them, so they will be relatively  static.

Br,
Laci

**Comment by jkimalane** [comment] 2019-11-08 09:34
Any news about merging your changes to mainline?

**Comment by szemere** [comment] 2019-11-11 12:40
Dear @jkimalane ,
 I have found evidence, that the hiredis library is having issues with tracking the messges in pipelining mode in case of connection lost. This can lead to message loss in syslog-ng, or unnecessary waiting for acknowledgement on an already lost message.
 Redis pipelining protocol uses a 20 character random string to uniquely identify each batch, however the hiredis lib do not propagate it to the caller site.
 Currently I am testing the lib and the redis server with manually indicated connection losses to see what should be implemented on the syslog-ng site.

Br,
Laci

**Comment by jkimalane** [comment] 2019-11-25 14:48
And again, any news? Is the bug discovered in hiredis library show stopper?

**Comment by szemere** [comment] 2019-12-06 14:41
Hello @jkimalane,
 I would not call it strictly a bug. It is a design choice from the hiredis lib creators. I have some plans to circumvent it. (Which is mainly just to purge it all :) and reconnect with a clean context)
 Currently I dropped the batch support part from the PR, so we can merge the rest of the refactors before the release. It still gives us a pretty decent performance improvement.

Br,
Laci

**Comment by jkimalane** [comment] 2019-12-06 15:19
Hi @szemere ,
Thanks for the update but for us the lack of support for pipelined request is a show stopper. Changes you have made in redis plugin code are needed, good and fix multiple issues but I'm not sure if they are enough to give us the performance boost we need. Maybe next release after this one will include redis pipelining support, till then we plan to implement simple and dummy proxy interface to pass messages from syslog-ng to redis with pipelining :)

**Comment by alltilla** [comment] 2020-01-07 12:29
Closing in favor of #2633, which is a feature request to implement batching in redis.

**Closed by alltilla** 2020-01-07 12:29 UTC
Labels: question
