### ISSUE TITLE
TLS SYSLOGs not received. SYSLOG-NG keeps restarting

### ISSUE THREAD

**Issue by villieb** [syslog-ng/syslog-ng#3360] opened 2020-07-21 10:02 UTC
Hi, I hope I am posting this in the right location and in the right format.

I'm experiencing an issue where I've configured SYSLOG-NG to listen on 6514 and to use TLS

```
options {
};

######
# sources
source syslog_ports {
udp();
tcp();
syslog();
};

# source for TLS - 6514
source tls_source {
network(ip(0.0.0.0) transport("tls") port(6514)
tls( key-file("/home/myuser/certs/syslog_server1.mydomain.net.key")
     cert-file("/home/myuser/certs/syslog_server1.mydomain.net.cer")
     peer-verify(optional-untrusted))
); };

# Destination for Traffic events
destination traffic_log { file("/var/log/syslog-ng/new/${HOST}_${YEAR}_${MONTH}_${DAY}_${HOUR}.log"
owner("root")
group("myuser")
perm(0640)); };


# Destination for Change events
destination change_log { file("/var/log/firewall_assurance/change_logs/${HOST}_${YEAR}_${MONTH}_${DAY}_${HOUR}.log"
owner("root")
group("myuser")
perm(0640)); };

# filter for traffic filter
filter f_traffic_log {
match("-106100:|RT_FLOW_SESSION_CLOSE|RT_FLOW_SESSION_CREATE|00257|traffic|TRAFFIC|Enforced|Connection_Allowed|t_nettraffic|VPN-1") and not match("[Dd]eny|[Dd]enied|DENY");};

# filter for change events
filter f_change_log {
match("notification-00001:|notification-00018:|notification-00012:|subtype=config|subtype=system|_CFG_AUDIT_|111008:|,CONFIG,|,config,") and not match("url-filtering");};


#local logger
#change events logger
log { source(syslog_ports); filter (f_change_log); destination(change_log);};
log { source(tls_source); filter (f_change_log); destination(change_log);};


#traffic events logger
log { source(syslog_ports); filter (f_traffic_log); destination(traffic_log);};
log { source(tls_source); filter (f_change_log); destination(traffic_log);};

```
However, when my client (I don't have visibility of their configuration) sends SYSLOGs on 6514, I do not see logs being saved.

Looking through /var/log/messages/ I see these messages being repeated over and over again...

```
Jul 20 10:53:59 localhost syslog-ng[148729]: syslog-ng starting up; version='3.6.4'
Jul 20 10:53:59 syslog_server1 kernel: syslog-ng[148679]: segfault at 4 ip 00007f3ea6bf4594 sp 00007fff60500868 error 4 in libsyslog-ng-3.6.so.0.0.0[7f3ea6ba0000+92000]
Jul 20 10:53:59 syslog_server1 systemd[1]: syslog-ng.service: main process exited, code=killed, status=11/SEGV
Jul 20 10:53:59 syslog_server1 systemd[1]: Unit syslog-ng.service entered failed state.
Jul 20 10:53:59 syslog_server1 systemd[1]: syslog-ng.service failed.
Jul 20 10:53:59 syslog_server1 systemd[1]: syslog-ng.service holdoff time over, scheduling restart.
Jul 20 10:53:59 syslog_server1 systemd[1]: Stopped System Logger Daemon.
Jul 20 10:53:59 syslog_server1 systemd[1]: Starting System Logger Daemon...
Jul 20 10:53:59 syslog_server1 syslog-ng[148729]: [2020-07-20T10:53:59.906355] WARNING: the match() filter without the use of the value() option is deprecated and hinders performance, please use a more specific filter like message() and/or program() instead.;
Jul 20 10:53:59 syslog_server1 systemd[1]: Started System Logger Daemon.
```

**Comment by Kokan** [comment] 2020-07-21 10:27
It seems your syslog-ng crashes:
```
Jul 20 10:53:59 syslog_server1 kernel: syslog-ng[148679]: segfault at 4 ip 00007f3ea6bf4594 sp 00007fff60500868 error 4 in libsyslog-ng-3.6.so.0.0.0[7f3ea6ba0000+92000]
``

Could you please provide a backtrace for the segfault ?
Please if possible als try to upgrade syslog-ng 3.6 is quit old, and it is possible that your current issue is already fixed.

**Comment by villieb** [comment] 2020-07-23 11:42
Thanks for responding. I've upgraded: 

```
# syslog-ng --version
syslog-ng 3 (3.28.1)
Config version: 3.22
Installer-Version: 3.28.1
Revision:
Compile-Date: Jun 25 2020 06:52:31
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: kvformat,basicfuncs,json-plugin,csvparser,xml,dbparser,graphite,stardate,cryptofuncs,tfgetent,timestamp,appmodel,disk-buffer,afsocket,linux-kmsg-format,afprog,afuser,system-source,cef,examples,add-contextual-data,confgen,tags-parser,map-value-pairs,hook-commands,syslogformat,afstomp,sdjournal,pseudofile,affile
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

However, when restarting the service I see in the journatlctl

```
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: [2020-07-23T12:34:00.890026] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.28 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.6'
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: Error parsing afsocket, File "/home/mysuser/certs/syslog_server1.mydomain.net.key" not found: Permission denied in /etc/syslog-ng/conf.d/custom-syslog-ng.conf:33:13-33:72:
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 28 ip(0.0.0.0)
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 29                      port(6514)
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 30                      transport("tls")
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 31                      tls(
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 32                              ca-dir("/home/mysuser/certs")
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 33---->                         key-file("/home/mysuser/certs/syslog_server1.mydomain.net.key")
Jul 23 12:34:00 syslog_server1 systemd[1]: syslog-ng.service: main process exited, code=exited, status=1/FAILURE
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 33---->                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 34                              cert-file("/home/mysuser/certs/syslog_server1.mydomain.net.cer")
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 35                              peer-verify(optional-untrusted)
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 36                      )
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 37              );
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 38      };
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: Included from /etc/syslog-ng/syslog-ng.conf:71:1-71:1:
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 66      log { source(s_sys); filter(f_cron); destination(d_cron); };
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 67
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 68
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 69      # Source additional configuration files (.conf extension only)
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 70      @include "/etc/syslog-ng/conf.d/*.conf"
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 71---->
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 71----> ^
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 72
Jul 23 12:34:00 syslog_server1 syslog-ng[60939]: 73      # vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
Jul 23 12:34:00 syslog_server1 systemd[1]: Failed to start System Logger Daemon.
Jul 23 12:34:00 syslog_server1 systemd[1]: Unit syslog-ng.service entered failed state.
Jul 23 12:34:00 syslog_server1 systemd[1]: syslog-ng.service failed.
Jul 23 12:34:01 syslog_server1 systemd[1]: syslog-ng.service holdoff time over, scheduling restart.
Jul 23 12:34:01 syslog_server1 systemd[1]: Stopped System Logger Daemon.
Jul 23 12:34:01 syslog_server1 systemd[1]: start request repeated too quickly for syslog-ng.service
Jul 23 12:34:01 syslog_server1 systemd[1]: Failed to start System Logger Daemon.
Jul 23 12:34:01 syslog_server1 systemd[1]: Unit syslog-ng.service entered failed state.
Jul 23 12:34:01 syslog_server1 systemd[1]: syslog-ng.service failed.
```

I a little new to linux - I followed the guide at https://www.syslog-ng.com/community/b/blog/posts/installing-latest-syslog-ng-on-rhel-and-other-rpm-distributions to upgrade and the guide at https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.22/mutual-authentication-using-tls to configure the syslog.conf file

Thanks

**Comment by czanik** [comment] 2020-07-23 11:46
You have Linux capabilities enabled and you try to open a file not owned by root.

I guess this blog covers your problem: https://www.syslog-ng.com/community/b/blog/posts/working-around-linux-capabilities-problems-for-syslog-ng

**Comment by villieb** [comment] 2020-07-23 13:17
It seems so yes - however I can't turn it off...

I've changed to a different server to see if was my environment.

When issuing "syslog-ng --no-caps" syslog seems to start, but not listening on 6514

modifying /usr/lib/systemd/system/syslog-ng.service to include the option --no-caps

ExecStart=/usr/sbin/syslog-ng -F --no-caps  -p /var/run/syslogd.pid

In journalctl I see the same "error parsing afsocket" message. 

I don't have a file /etc/sysconfig/syslog-ng - I created one with the content 

SYSLOGNG_OPTS="--caps cap_sys_admin,cap_chown,cap_dac_override,cap_net_bind_service,cap_fowner=eip"

Restarting the syslog-ng service gives me the same "Error parsing afsocket" message

**Comment by villieb** [comment] 2020-07-23 14:08
I also changed the permission of the cert files to root (chown root:root) 

I also did this:

semanage fcontext -a -t cert_t -s system_u syslog-server1.mydomain.net.cer 
semanage fcontext -a -t cert_t -s system_u syslog-server1.mydomain.net.key
restorecon -vF syslog-server1.mydomain.net.cer 
restorecon -vF syslog-server1.mydomain.net.key

Same "Error parsing afsocket" message

**Comment by czanik** [comment] 2020-07-23 14:34
Before touching any of the configuration files I'd recommend to localize the problem from the command line:
```
syslog-ng -F --no-caps
```
This disables capabilities support within syslog-ng. If it works, then make sure that --no-caps, or its longer, more restrictive form is properly added to your startup configuration.
If the problem remains, you should also temporarily disable SELinux:
```
setenforce 0
```
If it works, you should re-enable SELinux and take a second look at its configuration.

**Comment by gaborznagy** [comment] 2020-09-08 14:19
Hi @villieb!

Did you manage to find the cause of the issue?

**Comment by gaborznagy** [comment] 2020-09-17 10:11
I'm closing this issue for now. If anything comes up, feel free to comment and we reopen it.

**Closed by gaborznagy** 2020-09-17 10:11 UTC
Labels: question
