### ISSUE TITLE
Possible memory leaks, etc.

### ISSUE THREAD

**Issue by Stefan-Ghinea** [syslog-ng/syslog-ng#3497] opened 2020-11-27 10:42 UTC
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.30.1)
Config version: 3.29
Installer-Version: 3.30.1
Revision: 
Compile-Date: Nov 26 2020 11:41:33
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: appmodel,graphite,cryptofuncs,tags-parser,examples,tfgetent,afstomp,disk-buffer,syslogformat,pseudofile,afprog,add-contextual-data,secure-logging,azure-auth-header,map-value-pairs,stardate,cef,affile,xml,afuser,timestamp,linux-kmsg-format,kvformat,afsocket,confgen,dbparser,json-plugin,basicfuncs,hook-commands,system-source,csvparser,mod-python
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

Built from source and ran manually with default config:
```bash
sudo /usr/local/sbin/syslog-ng -F --enable-core --cfgfile /usr/local/etc/syslog-ng.conf
```

## Platform
Ubuntu 20.04.1 LTS x86_64

# Issue
## Failure
Memory consumption appears to be always increasing when monitoring it.

## Steps to reproduce
Constantly monitoring the memory consumption with the aid of ps:
```bash
while true; do ps -o pid,comm,vsz,rss ax | grep syslog-ng | awk '{print $4}' >> mem.log; tail -n1 mem.log; sleep 10; done
```

While writing to the logs for some time with the aid of a script:
```bash
#!/bin/sh
i=0
while [ "$i" -lt 1440 ] # this is loop1 for 2h at 5s
do
sleep 5
logger -p error "$i"
echo "log error: $i"
i=`expr $i + 1`
done
```

Or starting syslog-ng with valgrind and after sending logs for some time stopping the process (Ctrl+C) to obtain the leak summary:
```bash
sudo /usr/bin/valgrind --leak-check=yes --log-file=/var/log/valgrind-syslog.log /usr/local/sbin/syslog-ng -F --enable-core --cfgfile /usr/local/etc/syslog-ng.conf
```

## Configuration
```
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.30
@include "scl.conf"

source s_local {
	system();
	internal();
};

source s_network {
	default-network-drivers(
		# NOTE: TLS support
		#
		# the default-network-drivers() source driver opens the TLS
		# enabled ports as well, however without an actual key/cert
		# pair they will not operate and syslog-ng would display a
		# warning at startup.
		#
		#tls(key-file("/path/to/ssl-private-key") cert-file("/path/to/ssl-cert"))
	);
};

destination d_local {
	file("/var/log/messages");
	file("/var/log/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
};

log {
	source(s_local);

	# uncomment this line to open port 514 to receive messages
	#source(s_network);
	destination(d_local);
};
```

## Input and output logs (if possible)
Memory consumption increases when sending logs for 2 and 4 hours:
2h: 9408 -> 9484
4h: 9372 -> 9444

Valgrind leak summary after sending logs for 2 and 4 hours as well as after only starting and stopping syslog-ng (0h):
0h:
```
==42116== LEAK SUMMARY:
==42116==    definitely lost: 320 bytes in 10 blocks
==42116==    indirectly lost: 2,423 bytes in 30 blocks
==42116==      possibly lost: 776 bytes in 3 blocks
==42116==    still reachable: 47,063 bytes in 123 blocks
==42116==         suppressed: 0 bytes in 0 blocks
```
2h:
```
==42170== LEAK SUMMARY:
==42170==    definitely lost: 320 bytes in 10 blocks
==42170==    indirectly lost: 2,423 bytes in 30 blocks
==42170==      possibly lost: 472 bytes in 2 blocks
==42170==    still reachable: 46,927 bytes in 121 blocks
==42170==         suppressed: 0 bytes in 0 blocks
```
4h:
```
==46893== LEAK SUMMARY:
==46893==    definitely lost: 320 bytes in 10 blocks
==46893==    indirectly lost: 2,423 bytes in 30 blocks
==46893==      possibly lost: 472 bytes in 2 blocks
==46893==    still reachable: 46,927 bytes in 121 blocks
==46893==         suppressed: 0 bytes in 0 blocks
```

[ps-2h.log](https://github.com/syslog-ng/syslog-ng/files/5607380/ps-2h.log)
[ps-4h.log](https://github.com/syslog-ng/syslog-ng/files/5607382/ps-4h.log)
[valgrind-0h.log](https://github.com/syslog-ng/syslog-ng/files/5607383/valgrind-0h.log)
[valgrind-2h.log](https://github.com/syslog-ng/syslog-ng/files/5607384/valgrind-2h.log)
[valgrind-4h.log](https://github.com/syslog-ng/syslog-ng/files/5607385/valgrind-4h.log)

**Comment by szemere** [comment] 2020-11-27 11:51
Hello @Stefan-Ghinea ,
 thank you for the detailed report. I will check the attached Valgrind logs. (and will also generate some locally)
 In the meantime could you please also examine the output of the `syslog-ng-ctl stats` output in your environment? Our experience shows that Valgrind sometimes falsely reports some internal messaging queues.

Br,
Laci

**Comment by Stefan-Ghinea** [comment] 2020-11-27 13:16
Hello @szemere,

Here is the requested `syslog-ng-ctl stats` output:
```
SourceName;SourceId;SourceInstance;State;Type;Number
global;internal_queue_length;;a;processed;0
global;scratch_buffers_count;;a;queued;12
src.internal;s_local#2;;a;processed;1
src.internal;s_local#2;;a;stamp;1606482889
global;scratch_buffers_bytes;;a;queued;0
center;;received;a;processed;2
center;;queued;a;processed;4
global;msg_clones;;a;processed;1
destination;d_local;;a;processed;4
source;s_local;;a;processed;2
global;internal_source;;a;dropped;0
global;internal_source;;a;queued;0
global;sdata_updates;;a;processed;0
global;payload_reallocs;;a;processed;2
```

Best regards,
Stefan

**Comment by Kokan** [comment] 2020-11-27 16:14
Most of these leaks are one time leaks only, meaning they are leaked but not per message or periodically. As such they are not the cause of increasing memory usage. This can be seen also in valgrind reports, as the amount of leaked data is not increased even after 2 or 4 hour (actually decreased, possibly lost).

Yet ps still reports increased memory usage, this could be a result for example of caching memory by malloc for example.
Does this cause you additional issue ? like triggering oom kiiler or crash ?

A leak regarding stats counter is leaked per reload, also there is a proposed fix for that:  https://github.com/syslog-ng/syslog-ng/pull/3446 with fix.

**Comment by Kokan** [comment] 2020-12-12 14:09
The leak connected to stats counters fix is merged, the rest of the leaks only one time leaks, so the memory usage should not increase.

**Closed by Kokan** 2020-12-12 14:09 UTC
Labels: bug
