### ISSUE TITLE
v3.5.6  source code 

### ISSUE THREAD

**Issue by nzubarev122** [syslog-ng/syslog-ng#3918] opened 2022-02-15 09:38 UTC
i need to configurate from source code , https://github.com/syslog-ng/syslog-ng/archive/refs/tags/v3.5.6.tar.gz

3.5.6 its latest version.

skip_submodules=1 ./autogen.sh
#%configure --with-ivykis=system
make && make install

OUTput:

cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.5.6
make DESTDIR=/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-32.el7.x86_64 install
make --no-print-directory install-recursive
GEN doc/man/syslog-ng.8
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
make[2]: *** [doc/man/syslog-ng.8] Error 4
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.nVWAJ1 (%install)
how can i exclude docbook from configure ?

**Comment by MrAnno** [comment] 2022-02-15 09:49
The latest syslog-ng version is v3.35.1:
https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-3.35.1/syslog-ng-3.35.1.tar.gz

Manpages can be disabled with `./configure --disable-manpages ...`

In case you are forced to stay on v3.5.6, this flag does not exist in that version. You have to install `docbook-style-xsl` and `libxslt` that contains the necessary stylesheet.

**Comment by nzubarev122** [comment] 2022-02-15 10:47
++ basename ./config.sub
+ /usr/bin/cp -fv /usr/lib/rpm/redhat/config.sub ./config.sub
'/usr/lib/rpm/redhat/config.sub' -> './config.sub'
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-manpages --with-ivykis=system



CLD     syslog-ng/syslog-ng-ctl
  GEN      doc/man/syslog-ng.8
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
make[2]: *** [doc/man/syslog-ng.8] Error 4
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.8Lja6z
+ umask 022
+ cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD
+ '[' /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64 '!=' / ']'
+ rm -rf /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
++ dirname /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
+ mkdir -p /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT
+ mkdir /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
+ cd syslog-ng-3.5.6
+ cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.5.6
+ make DESTDIR=/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64 install
make --no-print-directory install-recursive
  GEN      doc/man/syslog-ng.8
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
make[2]: *** [doc/man/syslog-ng.8] Error 4
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.8Lja6z (%install)


Please help

**Comment by nzubarev122** [comment] 2022-02-15 10:47
> ++ basename ./config.sub
> 
> * /usr/bin/cp -fv /usr/lib/rpm/redhat/config.sub ./config.sub
>   '/usr/lib/rpm/redhat/config.sub' -> './config.sub'
> * ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-manpages --with-ivykis=system
> 
> CLD syslog-ng/syslog-ng-ctl GEN doc/man/syslog-ng.8 warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl" cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl make[2]: *** [doc/man/syslog-ng.8] Error 4 make[1]: *** [all-recursive] Error 1 make: *** [all] Error 2
> 
> * exit 0
>   Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.8Lja6z
> * umask 022
> * cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD
> * '[' /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64 '!=' / ']'
> * rm -rf /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
>   ++ dirname /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
> * mkdir -p /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT
> * mkdir /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
> * cd syslog-ng-3.5.6
> * cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.5.6
> * make DESTDIR=/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64 install
>   make --no-print-directory install-recursive
>   GEN      doc/man/syslog-ng.8
>   warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
>   cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
>   make[2]: *** [doc/man/syslog-ng.8] Error 4
>   make[1]: *** [install-recursive] Error 1
>   make: *** [install] Error 2
>   error: Bad exit status from /var/tmp/rpm-tmp.8Lja6z (%install)
> 
> Please help

++ basename ./config.sub

/usr/bin/cp -fv /usr/lib/rpm/redhat/config.sub ./config.sub
'/usr/lib/rpm/redhat/config.sub' -> './config.sub'
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-manpages --with-ivykis=system
CLD syslog-ng/syslog-ng-ctl
GEN doc/man/syslog-ng.8
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
make[2]: *** [doc/man/syslog-ng.8] Error 4
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.8Lja6z
umask 022
cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD
'[' /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64 '!=' / ']'
rm -rf /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
++ dirname /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
mkdir -p /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT
mkdir /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64
cd syslog-ng-3.5.6
cd /var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.5.6
make DESTDIR=/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILDROOT/syslog-ng-3.5.6-40.el7.x86_64 install
make --no-print-directory install-recursive
GEN doc/man/syslog-ng.8
warning: failed to load external entity "/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl"
cannot parse /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
make[2]: *** [doc/man/syslog-ng.8] Error 4
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.8Lja6z (%install)
Please help

**Comment by MrAnno** [comment] 2022-02-15 10:55
As I said, `--disable-manpages` is not available in v3.5.6.

>In case you are forced to stay on v3.5.6, this flag does not exist in that version. You have to install docbook-style-xsl and libxslt, which contains the necessary stylesheet.

**Comment by nzubarev122** [comment] 2022-02-15 11:09
> As I said, `--disable-manpages` is not available in v3.5.6.
> 
> > In case you are forced to stay on v3.5.6, this flag does not exist in that version. You have to install docbook-style-xsl and libxslt, which contains the necessary stylesheet.

Package docbook-style-xsl-1.78.1-3.el7.noarch already installed and latest version
Package libxslt-1.1.28-6.el7.x86_64 already installed and latest version

but its not work

**Comment by nzubarev122** [comment] 2022-02-16 14:53
3.2.2

../../lib/.libs/libsyslog-ng.so: undefined reference to `YYID'
collect2: error: ld returned 1 exit status
make[4]: *** [pdbtool] Error 1
make[4]: Leaving directory `/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.2.2/modules/dbparser'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.2.2/modules/dbparser'
make[2]: *** [install] Error 2
make[2]: Leaving directory `/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.2.2/modules/dbparser'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/var/lib/jenkins/workspace/build_rpm_syslogng.dsl/BUILD/syslog-ng-3.2.2/modules'
make: *** [install-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.UsFWby (%install)

**Comment by MrAnno** [comment] 2022-07-03 16:39
Duplicate of #3988

**Closed by MrAnno** 2022-07-03 16:39 UTC
Labels: question
