### ISSUE TITLE
segfaults when reloading syslog-ng in an infinite loop

### ISSUE THREAD

**Issue by lbudai** [syslog-ng/syslog-ng#656] opened 2015-08-25 11:56 UTC
```
#0  0x00007fcb155840d5 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007fcb1558783b in __GI_abort () at abort.c:91
#2  0x00007fcb120690c9 in os::abort(bool) () from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#3  0x00007fcb121e686f in VMError::report_and_die() () from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#4  0x00007fcb121e6e9a in crash_handler(int, siginfo*, void*) ()
   from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#5  <signal handler called>
#6  0x00007fcb12064366 in os::is_first_C_frame(frame*) () from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#7  0x00007fcb121e58f1 in VMError::report(outputStream*) ()
   from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#8  0x00007fcb121e63d3 in VMError::report_and_die() () from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#9  0x00007fcb12071524 in JVM_handle_linux_signal () from /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#10 <signal handler called>
#11 __pthread_mutex_lock (mutex=0x20) at pthread_mutex_lock.c:50
#12 0x00007fcb15e8a363 in mutex_lock (mutex=0xa0) at ../../../../syslog-ng.lbudai/lib/ivykis/src/mutex.h:38
#13 iv_event_post (this=0x33b50c0) at ../../../../syslog-ng.lbudai/lib/ivykis/src/iv_event.c:163
#14 0x00007fcb15b6df57 in g_list_foreach () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007fcb15e626c6 in _request_all_threads_to_exit () at ../syslog-ng.lbudai/lib/mainloop-worker.c:152
#16 main_loop_worker_sync_call (func=<optimized out>) at ../syslog-ng.lbudai/lib/mainloop-worker.c:349
#17 0x00007fcb15e8cd7f in iv_signal_event (_this=0x7fcb160c6100) at ../../../../syslog-ng.lbudai/lib/ivykis/src/iv_signal.c:170
#18 0x00007fcb15e8b8a9 in iv_event_raw_got_event (_this=0x7fcb160c6140)
    at ../../../../syslog-ng.lbudai/lib/ivykis/src/iv_event_raw_posix.c:89
#19 0x00007fcb15e8befc in iv_fd_poll_and_run (st=0x1a2fa70, to=<optimized out>)
    at ../../../../syslog-ng.lbudai/lib/ivykis/src/iv_fd.c:163
#20 0x00007fcb15e8c93c in iv_main () at ../../../../syslog-ng.lbudai/lib/ivykis/src/iv_main_posix.c:117
#21 0x00007fcb15e61d86 in main_loop_run () at ../syslog-ng.lbudai/lib/mainloop.c:504
#22 0x000000000040167b in main (argc=1, argv=0x7ffce17a7358) at ../syslog-ng.lbudai/syslog-ng/main.c:286
```

When syslog-ng iterate through the `exit_nofitication_list` in 
`_request_all_threads_to_exit` then we call the `log_threaded_dest_driver_stop_thread` in 
`lib/logthrdestdrv.c` which is set as a `terminate_func` at `logthrdestdrv.c:310`.
And in logthrdestdrv.c:303 we call `iv_event_post(&self->shutdown_event)`.
In `ivykis/src/iv_event.c:163` we want to lock a mutex, but that mutex is `0x20` ...

That mutex is part of the `shutdown_event` so that object is invalidated somehow somewhere by someone, but this is a different issue.

**Comment by MrAnno** [comment] 2023-02-24 09:41
I can't reproduce this anymore, even by enabling Java drivers. I'm closing this because, potentially, the problem no longer exists. Let me know if you disagree.

**Closed by MrAnno** 2023-02-24 09:41 UTC
Labels: bug
