### ISSUE TITLE
Push newer version to DockerHub

### ISSUE THREAD

**Issue by nikobearrr** [syslog-ng/syslog-ng#3198] opened 2020-03-27 13:21 UTC
I would like to use syslog-ng in docker and I would like to run the latest version (which at the time of writing is 3.26.1).

When I go to https://hub.docker.com/r/balabit/syslog-ng/tags I can see the "latest" has been updated 2 months ago, but the last tagged version is 3.24.1 
I would prefer not to use the "latest" tag as I want to be able to control my updates. 

I tried to find out when are new versions tagged, but I couldn't find such information. 
When can we expect to see 3.26.1 in dockerhub?

**Comment by szemere** [comment] 2020-03-27 14:24
Duplicate of #2941 
Which is unfortunately still open :(

I updated our images. Thank You for reporting it!

**Closed** 2020-03-27 14:24 UTC
Labels: bug

**Comment by nikobearrr** [comment] 2020-03-27 14:35
Hi @szemere, I have not seen the other issue, I should have done a better job at searching as I did try to find if there is a reason for that.
Thank you for updating the images
