### ISSUE TITLE
Not receiving syslog from server with RHEL 6.10 OS Version

### ISSUE THREAD

**Issue by AParida23** [syslog-ng/syslog-ng#4408] opened 2023-03-31 13:03 UTC
We are trying to collect syslog from a RHEL 6.10 OS. It is an on-prem server. However, we don't see the correct logs in the tcpdump or in the osnix index.
The same syslog configuration works for AIX 5.3, AIX 6 and RHEL 8 as well.

Config file used for RHEL 6 and RHEL 8:
"audit log
imfile #Load the imfile input module
authpriv.* /var/log/secure
/var/log/audit/audit.log
tag_audit_log:
audit_log
info
local6

. @@receivinghostip:514"

Here's the tcpdump from the RHEL 6.10 server:

13:50:28.597040 IP (tos 0x0, ttl 60, id 27717, offset 0, flags [DF], proto TCP (6), length 60)
sendinghostname.44476 > receivinghostname.shell: Flags [S], cksum 0xd4bf (correct), seq 447763177, win 14600, options [mss 1460,sackOK,TS val 2717269676 ecr 0,nop,wscale 7], length 0

The raw data that was received initially for the rhel 6 server :
RAWMSG=\xff\xf4\xff\xfd
PRI=13
MESSAGE=\xff\xf4\xff\xfd

The syslog-ng (version 2.40.0) is configured on a Splunk Heavy Forwarder and the logs collected are sent over to Splunk Cloud indexers via HEC.

Is this a compatibility issue between the OS version and syslog-ng?

**Comment by bazsi** [comment] 2023-03-31 15:27
On Fri, Mar 31, 2023, 15:03 AParida23 ***@***.***> wrote:

> We are trying to collect syslog from a RHEL 6.10 OS. It is an on-prem
> server. However, we don't see the correct logs in the tcpdump or in the
> osnix index.
> The same syslog configuration works for AIX 5.3, AIX 6 and RHEL 8 as well.
>
> Config file used for RHEL 6 and RHEL 8:
> "audit log
> imfile #Load the imfile input module
> authpriv.* /var/log/secure
> /var/log/audit/audit.log
> tag_audit_log:
> audit_log
> info
> local6
>
> . @@receivinghostip:514"
>
> Here's the tcpdump from the RHEL 6.10 server:
>
> 13:50:28.597040 IP (tos 0x0, ttl 60, id 27717, offset 0, flags [DF], proto
> TCP (6), length 60)
> sendinghostname.44476 > receivinghostname.shell: Flags [S], cksum 0xd4bf
> (correct), seq 447763177, win 14600, options [mss 1460,sackOK,TS val
> 2717269676 ecr 0,nop,wscale 7], length 0
>
> The raw data that was received initially for the rhel 6 server :
> RAWMSG=\xff\xf4\xff\xfd
> PRI=13
> MESSAGE=\xff\xf4\xff\xfd
>
> The syslog-ng (version 2.40.0) is configured on a Splunk Heavy Forwarder
> and the logs collected are sent over to Splunk Cloud indexers via HEC.
>
2.40.0 is not a syslog-ng version number.

Those bytes in RAWMSG seem to be binary, isn't it possible the client is
trying to send with  SSL enabled?


Is this a compatibility issue between the OS version and syslog-ng?
>
syslog-ng doesn't care as long as the client is using the proper format.
The syslog protocol is completely text based, so if you look at the payload
as captured by tcpdump it should be completely readable.

Bazsi

**Comment by AParida23** [comment] 2023-04-04 14:43
Thanks Bazsi.
I have asked the server team to check if they are sending the logs with SSL enabled. 
So, would you say that this issue is on the client side wherein they are not sending the logs in the correct format? Would you be able to let me know the correct format so I can forward it to the server team?

**Comment by bazsi** [comment] 2023-04-04 16:37
Normal syslog, rfc3164, over TCP or UDP should work. You can probably
configure syslog-ng to accept whatever they are sending now. It's just
strange that it starts with binary bytes as syslog is text based (unless of
course it is wrapped into TLS)

**Comment by bazsi** [comment] 2023-04-18 05:50
Closing because of inactivity.

**Comment by AParida23** [comment] 2023-04-18 13:27
Could you please let me know or direct me to any online document which explains how to configure syslog to accept whatever they are sending? Also, will that impact the other rhel servers' logs being received correctly by syslog-ng?

**Comment by AParida23** [comment] 2023-04-19 14:20
Hi Bazsi,

Thank you. It would be great if you could help me with the steps to do the packet capture.

**Comment by AParida23** [comment] 2023-04-25 19:28
Hi Bazsi,

Could you please provide me with any steps or documentation to do the packet capture?

**Comment by bazsi** [comment] 2023-04-26 18:07
First of all, we have a discord server for more interactive communication.

https://discord.gg/E65kP9aZGm

To do a packet capture, run tcpdump with the following arguments as root:


$ tcpdump -peni <name-of-your-interface> -s0 -w packets.pcap port 514

Tcpdump will save all incoming packets on port 514 to packets.pcap

If you want to capture the logs for one specific IP address, then use this:

$ tcpdump -peni <name-of-your-interface> -s0 -w packets.pcap port 514 and
host <IP address>

If there's a single host causing problems, focus on that.

Generate a log entry to reproduce the problem and then send the pcap to me
privately or post to discord, along with what you think syslog-ng does
incorrectly with that specific log entry.

Thanks

**Comment by AParida23** [comment] 2023-05-08 19:44
Hi Bazsi,

I have sent you the packet capture to your email address. Please check and let me know. Thanks.

**Comment by bazsi** [comment] 2023-05-20 09:28
We've discussed this in person and the root cause seems to have been a firewall issue, not related to syslog-ng per se.

closing.

**Closed by bazsi** 2023-05-20 09:28 UTC
