### ISSUE TITLE
Daemon stops reading from network source following charset decoding error

### ISSUE THREAD

**Issue by Echo-bash** [syslog-ng/syslog-ng#4083] opened 2022-07-18 09:03 UTC
# syslog-ng
## Version of syslog-ng

[root@syslog-ng ~]# syslog-ng --version
syslog-ng 3 (3.37.1)
Config version: 3.35
Installer-Version: 3.37.1
Revision: 
Compile-Date: Jun  8 2022 07:08:52
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,dbparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,kafka
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
## Platform

Linux syslog-ng 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
## Debug bundle

# Issue
Daemon stops reading from network source following charset decoding error
## Failure
[2022-07-16T17:05:56.175081] Invalid byte sequence or other error while converting input, skipping character; encoding='GB18030', char='0x97

## Configuration

@version: 3.37
@include "scl.conf"
options {
       flush-lines(10000);
       log-fetch-limit(10000);
       log-fifo-size(20480);
       log-msg-size(204800);
       use-dns(no);
       dns-cache(no);
       create_dirs(yes);
       threaded(yes);
};

source s_network {
        network(
        ip("0.0.0.0")
        port(514)
        transport("udp")
        keep-hostname(no)
    );
};
source s_network_gb {
        network(
        ip("0.0.0.0")
        port(515)
        transport("udp")
        encoding("GB18030")
        keep-hostname(no)
    );
};

destination d_kafka {
  channel {
    rewrite {
      set("${HOST}"    value(".eventv1.host"));
      set("1"          value(".eventv1.@version"));
      set("${R_ISODATE}" value(".eventv1.@timestamp") condition("${.eventv1.@timestamp}" eq ""));
      set("${PROGRAM}" value(".eventv1.program")    condition("${.eventv1.program}" eq ""));
      set("${PID}" value(".eventv1.pid")    condition("${.eventv1.pid}" eq ""));
      set("${LEVEL_NUM}" value(".eventv1.level")    condition("${.eventv1.level}" eq ""));
      set("${MESSAGE}" value(".eventv1.message")    condition("${.eventv1.message}" eq ""));
      set("generic"    value(".eventv1.type")       condition("${.eventv1.type}" eq ""));
    };
    destination {
      kafka-c(config(queue.buffering.max.ms("1000"))
            bootstrap-servers("10.76.230.155:39092,10.76.230.156:39092,10.76.230.157:39092")
            topic("syslog")
            fallback_topic(syslog)
            message("$(format-json --key .eventv1.* --rekey .eventv1.* --shift 9)"));
    };
  };
};

log {
  source(s_network);
  source(s_network_gb);
  destination(d_kafka);
};

**Comment by alltilla** [comment] 2022-07-18 11:22
Hi @hebaodanroot 

Thanks for opening this issue ticket! :)

For further investigation, can you share the following?
  1. Do you have an example input log, which reproduces the problem?
  2. Can you run syslog-ng with `-Fedtv` and reproduce the problem? This would give us more info.
  3. Can you build from source? If so, I would send some changes, which would give us more info about the problem.
  4. Can you share your `iconv` version?
  5. Can I find/use your platform somewhere (`Linux syslog-ng 3.10.0-862.el7.x86_64 https://github.com/syslog-ng/syslog-ng/pull/1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)? I would like to use an environment which is as close as possible to yours.

I tried to reproduce your problem, but in my environment the `0x97` character got handled properly, so we probably have some differences in our environments (probably iconv).

Cheers,
Attila

**Comment by hebaodanroot** [comment] 2022-07-19 02:29
1.logs
![image](https://user-images.githubusercontent.com/45256479/179650895-afd7cd3e-34a1-4833-ae73-cc8283fc7b6c.png)
2.yum
https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng337/repo/epel-7/czanik-syslog-ng337-epel-7.repo
3.iconv version
![image](https://user-images.githubusercontent.com/45256479/179650994-a54c12cb-3f8b-4428-a345-1a2c1ff54fe7.png)
4.OS
![image](https://user-images.githubusercontent.com/45256479/179651122-b9fa3aab-3d44-4cda-9655-c39be56aad3a.png)

**Comment by hebaodanroot** [comment] 2022-07-19 15:41
Thank you. Let me test it

**Comment by hebaodanroot** [comment] 2022-07-20 15:43
This bug seems to have been fixed, and the log is not broken
![image](https://user-images.githubusercontent.com/45256479/180024641-cea7e8cf-b5c2-450c-b4b8-2710f6106104.png)
![image](https://user-images.githubusercontent.com/45256479/180025464-6df771ad-0a5d-493b-9ac0-d949ca0a3f30.png)

**Comment by alltilla** [comment] 2022-07-21 07:59
If we reached `log-msg-size()` we would have seen error or notice messages about it.

To investigate why the character parsing failed, we need an example incoming message, which reproduces the error. Can you pinpoint which message caused this error? If not, you can start syslog-ng in the foreground, with trace logs enabled: `syslog-ng -Fet 2>&1 | tee -i syslog-ng-trace.log` and also capture the udp traffic.

After the `invalid byte sequence` error happens, you will see similar logs:
```
[2022-07-21T09:56:57.192721] Setting value; name='PROGRAM', value='program', type='string', msg='0x7fb1b8014820', rcptid='31'
[2022-07-21T09:56:57.192770] Setting value; name='LEGACY_MSGHDR', value='program ', type='string', msg='0x7fb1b8014820', rcptid='31'
[2022-07-21T09:56:57.192778] Setting value; name='MESSAGE', value='almafa', type='string', msg='0x7fb1b8014820', rcptid='31'
```

That will be the the problematic message. After that, you can check the udp traffic, and isolate the byte sequence, which contains the problematic message. Hopefully it produces the problem consitently, so we can investigate it.

**Comment by hebaodanroot** [comment] 2022-07-21 09:38
I also want to give you the log, but I found that the log is missing seriously, and the faulty syslog input log cannot be located.
This is the log generated by filtering 10.76.230.114，
![image](https://user-images.githubusercontent.com/45256479/180181902-2e50b41e-c657-438b-b8d3-099dbc43f383.png)
Here are the startup parameters
![image](https://user-images.githubusercontent.com/45256479/180182165-87058046-257a-4aff-a72c-e6a5d8ef2daf.png)
This is the log generated during
![image](https://user-images.githubusercontent.com/45256479/180182308-0a3f3dfd-0fc3-4aa5-a6de-eae2d4fe61fc.png)

**Comment by hebaodanroot** [comment] 2022-07-21 09:54
10.76.230.114 device sends syslog log to UDP515 port, GB18030 encoding，10.76.230.50 device sends syslog logs to UDP514 port, encoding no.
![image](https://user-images.githubusercontent.com/45256479/180184293-12dedeed-cb4f-4d2c-b319-6d8e7dacc0a0.png)

**Comment by alltilla** [comment] 2022-07-21 09:59
Okay, let me prepare some additional logging just for this investigation :)

**Comment by alltilla** [comment] 2022-07-21 10:21
I have added some temporary logs for this investigation only. For the code, see: https://github.com/alltilla/syslog-ng/commit/f423e0a19b3080263bc0e7b5adca4e582d664473
You do not have to enable trace logging with this change, these new messages will appear on the error level.

Example output:
```
[2022-07-21T12:02:53.473398] Invalid byte sequence, skipping character; encoding='GB18030', char='0x80', offset='12'
[2022-07-21T12:02:53.473432] Debug for hebaodanroot; offset='0', char='0x70'
[2022-07-21T12:02:53.473437] Debug for hebaodanroot; offset='1', char='0x72'
[2022-07-21T12:02:53.473441] Debug for hebaodanroot; offset='2', char='0x6f'
[2022-07-21T12:02:53.473446] Debug for hebaodanroot; offset='3', char='0x67'
[2022-07-21T12:02:53.473449] Debug for hebaodanroot; offset='4', char='0x72'
[2022-07-21T12:02:53.473454] Debug for hebaodanroot; offset='5', char='0x61'
[2022-07-21T12:02:53.473458] Debug for hebaodanroot; offset='6', char='0x6d'
[2022-07-21T12:02:53.473461] Debug for hebaodanroot; offset='7', char='0x20'
[2022-07-21T12:02:53.473465] Debug for hebaodanroot; offset='8', char='0x74'
[2022-07-21T12:02:53.473469] Debug for hebaodanroot; offset='9', char='0x65'
[2022-07-21T12:02:53.473473] Debug for hebaodanroot; offset='10', char='0x73'
[2022-07-21T12:02:53.473478] Debug for hebaodanroot; offset='11', char='0x74'
[2022-07-21T12:02:53.473482] Debug for hebaodanroot; offset='12', char='0x80'
[2022-07-21T12:02:53.473485] Debug for hebaodanroot; offset='13', char='0x32'
[2022-07-21T12:02:53.473493] Debug for hebaodanroot; offset='14', char='0x33'
[2022-07-21T12:02:53.473497] Debug for hebaodanroot; offset='15', char='0x0a'
```

centos-7 packages:
[package-centos-7.zip](https://github.com/syslog-ng/syslog-ng/files/9158460/package-centos-7.zip)

From these, I hope that we can get the input message and reproduce the problem.

**Comment by hebaodanroot** [comment] 2022-07-21 15:15
![image](https://user-images.githubusercontent.com/45256479/180249926-2ebcda30-22ae-417a-9bca-d1e54e6b9e13.png)

**Comment by hebaodanroot** [comment] 2022-07-21 15:24
Could this be the problem caused by the same device sending two different encodings? My test environment uses the UTF-8 encoded linux server to send syslog logs with Chinese characters to the GB18030 encoded syslog-ng server and throws the same abnormal

**Comment by hebaodanroot** [comment] 2022-07-21 16:07
I found the problem, the original data does have the problem of mixed encoding of UTF-8 and GB18030. cause an error

**Comment by MrAnno** [comment] 2022-07-21 16:46
Senders with different incompatible encodings should be separated, if possible.
For example, adding a separate network source for each incompatible encoding could work.

We can't do much when the input is invalid considering the configured encoding. In that case, we try to drop invalid bytes sequences in the hope that the rest of the message will be valid.

(syslog-ng's internal representation is UTF-8, so when you specify an encoding in your sources, syslog-ng will try to decode it to UTF-8.)

You can always ensure your input remains valid as UTF-8 data by adding the `sanitize-utf8` flag to your sources. This flag replaces all invalid bytes with hex-encoded UTF-8 data, but it won't really help when you have to specify an `encoding()`.

**Comment by hebaodanroot** [comment] 2022-07-22 02:44
Then how to modify the configuration file, you can collect similar syslog logs, even if it is garbled, it doesn't matter, it is currently GB18030 encoding

**Comment by alltilla** [comment] 2022-07-22 07:03
Sorry I do not understand what you are asking, can you please rephrase your question? I think @MrAnno's answer explained what syslog-ng is able to do in your situation.

**Comment by Echo-bash** [comment] 2022-07-22 09:03
> 对不起，我不明白你在问什么，你能改写你的问题吗？我认为@MrAnno的回答解释了 syslog-ng 在您的情况下能够做什么。
As long as the decoding error does not affect the collection of syslog logs it is fine

**Comment by alltilla** [comment] 2022-07-22 10:59
I cannot say anything more: syslog-ng cannot handle an incoming log message with mixed encodings, neither could any text editor. Either you fix the message on the sender side, or you will get skipped characters and/or garbled message.

The fact, that the network source halted at an invalid message was a bug, but it will be fixed in #4084.

**Comment by MrAnno** [comment] 2022-07-22 13:45
We might have another option, but I think that won't be a real option for you:

You can omit the `encoding()` option, set the `flags(no-parse)` flag for your source, and operate syslog-ng in a very simplistic forwarder mode. That way, you can't use rewrite rules, parsers, filters that operate on the messages (at least you can't do that on log paths, where this source is used), but you can, at least, forward your invalidly-encoded messages to a destination.

I believe this would only postpone the problem because then you would have to deal with the invalid encoded data on the collector server (on the Kafka side).

**Comment by MrAnno** [comment] 2022-07-22 13:50
> As long as the decoding error does not affect the collection of syslog logs it is fine

With #4084, decoding errors will no longer affect your log collection flow. Invalid characters will be skipped, and receiving further messages will work properly once the invalid part is skipped.

**Comment by Echo-bash** [comment] 2022-07-22 14:39
> > 只要解码错误不影响 syslog 日志的收集就可以了
> 
> 使用#4084，解码错误将不再影响您的日志收集流程。无效的字节序列将被丢弃，一旦跳过无效部分，接收进一步的消息将正常工作。

OK，thanks，Will this be fixed in the next version?

**Comment by bazsi** [comment] 2022-07-28 09:45
I think we should include some kind of fallback sequence in the input if this happens. g_convert_with_fallback() for instance returns this sequence if there's no explicit fallback string:                       

```
gunichar ch = g_utf8_get_char (p);
                      insert_str = g_strdup_printf (ch < 0x10000 ? "\\u%04x" : "\\U%08x",
                                                    ch);
```

in our case, we don't have unicode characters (g_convert_with_fallback() does two conversions internally, one from source to utf8, and then from utf8 to output, in which case this happens if an utf8 character cannot be represented in the output.

In our case, we are converting from one to the other directly, so we only have 8 bit characters at a time, but inserting them as \xFF would be much better than silently dropping them. Or alternatively we could check if they are valid utf-8 sequences, because if they are, we could just do the right thing. I guess a similar problem happens pretty regularly in any non-utf8 systems out there. (I guess this may not work when the source encoding consumes the beginning of an utf8 sequence)

encoding() was originally meant to be used where the source can guarantee a specific encoding (for example Windows with UCS-2 files), without specifying the encoding option for syslog-ng, it remains in the original, mixed string, but that also means that your end system (e.g. the SIEM/elastic) would see the mixed encoding which may cause problems there.

With all this said, I'd love to see some kind of fallback mechanism, represent the broken string in the input, rather simply skipping it. And with that we can increase the log level of the error message to "debug" or even higher.

**Closed** 2022-08-24 12:48 UTC
Labels: bug
