### ISSUE TITLE
Network error while inserting into AMQP server

### ISSUE THREAD

**Issue by Maxpain177** [syslog-ng/syslog-ng#1377] opened 2017-03-07 23:24 UTC
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 3.9.1-2
Module-Directory: /usr/lib/syslog-ng/3.9
Module-Path: /usr/lib/syslog-ng/3.9
Available-Modules: graphite,csvparser,afsocket,date,afmongodb,mod-java,afamqp,kvformat,dbparser,cryptofuncs,cef,pseudofile,afprog,mod-python,afuser,syslogformat,linux-kmsg-format,add-contextual-data,sdjournal,affile,confgen,json-plugin,disk-buffer,afstomp,system-source,basicfuncs,geoip-plugin
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Platform
Debian 8.0 (inside a Docker)

# Issue

## Failure
Getting network errors when connecting to amqp server:
```
[2017-03-07T22:59:54.217024] Network error while inserting into AMQP server; driver='d_amqp#0', error='(unknown error)', time_reopen='60'
[2017-03-07T23:00:54.564680] Connecting to AMQP succeeded; driver='d_amqp#0'
````

## Steps to reproduce

1. start `syslog-ng` (inside a Docker)
2. start docker container with flag `--log-driver=syslog --log-opt syslog-address=tcp://127.0.0.1:514`
3. Waiting 2-3 minutes
4. Getting network connection errors (amqp), then reconnecting after 60 seconds.

## Configuration

```
$ cat /path/to/syslog-ng.conf
@version: 3.9.1

source s_network {
        network(ip(0.0.0.0) port(514));
};

destination d_amqp {
        amqp(
                vhost("/")
                host("127.0.0.1")
                port(5672)
                username("username")
                password("password")
                exchange("logs")
                exchange-type("direct")
                routing-key("")
                body("")
                persistent(yes)

                disk-buffer(
                        reliable(yes)
                        dir("/tmp/disk-buffer")
                        mem-buf-size(10000)
                        disk-buf-size(2000000)
                )
        );
};

log {
        source(s_network);
        destination(d_amqp);
};
```

## Input and output logs (if possible)

```
[2017-03-07T22:59:54.213716] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Using breakpad crash handler'
[2017-03-07T22:59:54.214713] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Setting breakpad minidump AppID = 10'
[2017-03-07T22:59:54.215635] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Forcing breakpad minidump interfaces to load'
[2017-03-07T22:59:54.217024] Network error while inserting into AMQP server; driver='d_amqp#0', error='(unknown error)', time_reopen='60'
[2017-03-07T22:59:54.231567] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Looking up breakpad interfaces from steamclient'
[2017-03-07T22:59:54.232554] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Calling BreakpadMiniDumpSystemInit'
[2017-03-07T22:59:54.282338] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Protocol version 48'
[2017-03-07T22:59:54.283759] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Exe version 1.1.2.7/Stdio (cstrike)'
[2017-03-07T22:59:54.284626] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Exe build: 13:12:29 Aug 29 2013 (6153)'
[2017-03-07T22:59:54.285522] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: STEAM Auth Server'
[2017-03-07T22:59:54.299871] Incoming log entry; line='<30>Mar  7 22:59:54 docker.gameserver_57[1906]: Server IP address 172.17.0.5:27017'
[2017-03-07T22:59:55.239442] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.'
[2017-03-07T22:59:55.273068] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: applicationmanager.cpp (3337) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index'
[2017-03-07T22:59:55.273955] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: applicationmanager.cpp (3337) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index'
[2017-03-07T22:59:55.274717] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: applicationmanager.cpp (3500) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0'
[2017-03-07T22:59:55.370195] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: Looking up breakpad interfaces from steamclient'
[2017-03-07T22:59:55.371355] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: Calling BreakpadMiniDumpSystemInit'
[2017-03-07T22:59:55.793441] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: '
[2017-03-07T22:59:55.808719] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: couldn\'t exec listip.cfg'
[2017-03-07T22:59:55.813317] Incoming log entry; line='<30>Mar  7 22:59:55 docker.gameserver_57[1906]: couldn\'t exec banned.cfg'
[2017-03-07T22:59:56.959062] Incoming log entry; line='<30>Mar  7 22:59:56 docker.gameserver_57[1906]: Connection to Steam servers successful.'
[2017-03-07T22:59:57.273062] Incoming log entry; line='<30>Mar  7 22:59:57 docker.gameserver_57[1906]:    VAC secure mode is activated.'
[2017-03-07T23:00:54.564680] Connecting to AMQP succeeded; driver='d_amqp#0'
```

**Comment by mitzkia** [comment] 2017-03-08 09:31
Hi, 

I can reproduce the `Network error while inserting into AMQP server; driver='d_amqp#0', error='(unknown error)', time_reopen='60'` error message when syslog-ng lost the connection with AMQP server. 

Could you check the AMQP server connection (or logs) when the following message is logged? 
Where did you run the AMQP server in same docker container, or in other one?

**Comment by Maxpain177** [comment] 2017-03-08 22:16
Hi, @mitzkia.

Connection between amqp server (rabbitmq inside a docker on digitalocean droplet) and docker container with syslog-ng (local machine) is stable (i checking with ping command)

**Comment by gaborznagy** [comment] 2020-01-10 14:56
We don't know the cause of connection lost between the AMQP server and the local syslog-ng.
Most likely it's a network issue.

Closing the ticket.
Contact us if you would like this issue to be reopened.

**Closed by gaborznagy** 2020-01-10 14:56 UTC
Labels: bug
