### ISSUE TITLE
"Syslog connection closed" but socket not closed

### ISSUE THREAD

**Issue by phemmer** [syslog-ng/syslog-ng#889] opened 2016-01-27 13:24 UTC
We recently saw an issue where syslog-ng (version 3.6.4 on FreeBSD 10.1) 
was configured with a `syslog()` source, received an invalid frame, shut 
down the connection, but the socket remained open. I was looking through 
the documented fixes in the versions since the one we're using, 
but nothing looks related.

```
2016-01-21T07:44:21-05:00 iad1gweb01.ecom.chewy.com     ERR 
syslog-ng[27090]: - Invalid frame header; header='' [meta sequenceId="389"]
2016-01-21T07:44:21-05:00 iad1gweb01.ecom.chewy.com  NOTICE 
syslog-ng[27090]: - Syslog connection closed; fd='19', 
client='AF_INET(127.0.0.1:59317)', local='AF_INET(127.0.0.1:601)' [meta 
sequenceId="390"]
```

```
# netstat -an|grep 59317
tcp4   81660      0 127.0.0.1.601 127.0.0.1.59317        ESTABLISHED
tcp4       0  48923 127.0.0.1.59317 127.0.0.1.601          ESTABLISHED
```

 From the netstat output (the buffer sizes), it looks like syslog-ng 
stopped reading from the socket, but didn't close it, and the 
application on the other end kept trying to write to it.

**Comment by MrAnno** [comment] 2016-02-01 09:04
Hi,

Thank you for opening this issue!

Unfortunately, I was unable to reproduce this socket-closing problem with syslog-ng-3.6.4 on FreeBSD. In my test environment, sockets are closed correctly after an invalid frame.

Could you paste your exact configuration?

**Comment by phemmer** [comment] 2016-02-24 22:17
Haven't forgotten about this, just on vacation at the moment and haven't had time to get back to it.
However when trying to reproduce ourselves, it was proving extremely difficult. However we are still seeing the issue in our production environment. Will probably get back onto trying to reproduce this early next week.

However this is our config:

```
@version:3.6
@include "scl.conf"

options {
    ts-format(iso); chain_hostnames(off); flush_lines(0); threaded(yes); keep-hostname(yes);
    create-dirs(yes);
    keep-timestamp(no);
    log-msg-size(65536);
    use-fqdn(yes);
};

template ChewyFormat {
    template("${ISODATE} ${HOST} $(uppercase $(padding $LEVEL 7)) ${MSGHDR}${MSGID:--} ${MSG} ${SDATA}\n");
    template_escape(no);
};

source s_system {
    system();
    internal();
    syslog(ip(127.0.0.1) transport("tcp") host-override("iad1gweb01.ecom.chewy.com"));
    syslog(ip(127.0.0.1) transport("udp") host-override("iad1gweb01.ecom.chewy.com"));
};

destination messages { file("/var/log/messages"); };
destination security { file("/var/log/security"); };
destination authlog { file("/var/log/auth.log"); };
destination maillog { file("/var/log/maillog"); };
destination xferlog { file("/var/log/xferlog"); };
destination cron { file("/var/log/cron"); };
destination debuglog { file("/var/log/debug.log"); };
destination consolelog { file("/var/log/console.log"); };
destination console { file("/dev/console"); };
destination allusers { usertty("*"); };

destination d_all { file("/var/log/all.log" template(ChewyFormat)); };

filter f_auth { facility(auth); };
filter f_authpriv { facility(authpriv); };
filter f_not_authpriv { not facility(authpriv); };
filter f_console { facility(console); };
filter f_cron { facility(cron); };
filter f_daemon { facility(daemon); };
filter f_ftp { facility(ftp); };
filter f_kern { facility(kern); };
filter f_lpr { facility(lpr); };
filter f_mail { facility(mail); };
filter f_security { facility(security); };
filter f_user { facility(user); };
filter f_uucp { facility(uucp); };
filter f_local0 { facility(local0); };
filter f_local1 { facility(local1); };
filter f_local2 { facility(local2); };
filter f_local3 { facility(local3); };
filter f_local4 { facility(local4); };
filter f_local5 { facility(local5); };
filter f_local6 { facility(local6); };
filter f_local7 { facility(local7); };

filter f_emerg { level(emerg); };
filter f_alert { level(alert..emerg); };
filter f_crit { level(crit..emerg); };
filter f_err { level(err..emerg); };
filter f_warning { level(warning..emerg); };
filter f_notice { level(notice..emerg); };
filter f_info { level(info..emerg); };
filter f_debug { level(debug..emerg); };
filter f_is_debug { level(debug); };
filter f_nodebug { level(info...emerg); };



log { source(s_system); filter(f_notice); filter(f_not_authpriv); destination(messages); };
log { source(s_system); filter(f_kern); filter(f_debug); destination(messages); };
log { source(s_system); filter(f_lpr); filter(f_info); destination(messages); };
log { source(s_system); filter(f_mail); filter(f_crit); destination(messages); };
log { source(s_system); filter(f_security); destination(security); };
log { source(s_system); filter(f_auth); filter(f_info); destination(authlog); };
log { source(s_system); filter(f_authpriv); filter(f_info); destination(authlog); };
log { source(s_system); filter(f_mail); filter(f_info); destination(maillog); };
log { source(s_system); filter(f_ftp); filter(f_info); destination(xferlog); };
log { source(s_system); filter(f_cron); destination(cron); };
log { source(s_system); filter(f_is_debug); destination(debuglog); };
log { source(s_system); filter(f_emerg); destination(allusers); };


log {
    source(s_system);
    destination(d_all);
    flags(flow-control);        # don't lose messages when destination is down
};

destination d_loghost {
	syslog("iad1glog01.ecom.chewy.com"
		frac-digits(3)
		log-fifo-size(10000)
	);
};
log { source(s_system); destination(d_loghost); };


destination d_nginx_error {
  file("/var/log/nginx-error.log" template("${MSG}\n"));
};
destination d_nginx_access {
  file("/var/log/nginx/access.log" template("${MSG}\n"));
};

filter f_nginx_error {
  program("nginx");
  level(warn..emerg);
};
filter f_nginx_access {
  program("nginx");
  level(debug..notice);
};

log { source(s_system); filter(f_nginx_error); destination(d_nginx_error); };
log { source(s_system); filter(f_nginx_access); destination(d_nginx_access); };
```

**Comment by MrAnno** [comment] 2016-02-25 08:10
Hello @phemmer,

Thank you for the config file. I'm going to make another try on this weekend.

**Comment by sriram0706** [comment] 2016-03-14 00:19
I tried to inject an invalid frame using scapy and the socket connection did terminate gracefully.

**Comment by MrAnno** [comment] 2020-12-12 13:41
The current codebase calls `close()` on the socket unconditionally after printing `Syslog connection closed`.
Closing.

**Closed by MrAnno** 2020-12-12 13:41 UTC
Labels: bug
